# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/AreaCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AreaCalculator(object):
    def setupUi(self, AreaCalculator):
        AreaCalculator.setObjectName("AreaCalculator")
        AreaCalculator.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(AreaCalculator)
        self.centralwidget.setObjectName("centralwidget")
        AreaCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AreaCalculator)
        self.menubar.setObjectName("menubar")
        self.menuFiguras = QtWidgets.QMenu(self.menubar)
        self.menuFiguras.setObjectName("menuFiguras")
        AreaCalculator.setMenuBar(self.menubar)
        self.actionCirculo = QtWidgets.QAction(AreaCalculator)
        self.actionCirculo.setObjectName("actionCirculo")
        self.actionTriangulo = QtWidgets.QAction(AreaCalculator)
        self.actionTriangulo.setObjectName("actionTriangulo")
        self.actionRectangulo = QtWidgets.QAction(AreaCalculator)
        self.actionRectangulo.setObjectName("actionRectangulo")
        self.actionCuadrado = QtWidgets.QAction(AreaCalculator)
        self.actionCuadrado.setObjectName("actionCuadrado")
        self.menubar.addAction(self.menuFiguras.menuAction())
        self.menuFiguras.addAction(self.actionCirculo)
        self.menuFiguras.addAction(self.actionTriangulo)
        self.menuFiguras.addAction(self.actionRectangulo)
        self.menuFiguras.addAction(self.actionCuadrado)
        
        self.retranslateUi(AreaCalculator)
        QtCore.QMetaObject.connectSlotsByName(AreaCalculator)

    def retranslateUi(self, AreaCalculator):
        _translate = QtCore.QCoreApplication.translate
        AreaCalculator.setWindowTitle(_translate("AreaCalculator", "Calculadora de Áreas"))
        self.menuFiguras.setTitle(_translate("AreaCalculator", "Figuras"))
        self.actionCirculo.setText(_translate("AreaCalculator", "Círculo"))
        self.actionTriangulo.setText(_translate("AreaCalculator", "Triángulo"))
        self.actionRectangulo.setText(_translate("AreaCalculator", "Rectángulo"))
        self.actionCuadrado.setText(_translate("AreaCalculator", "Cuadrado"))
